package world;

import gameObjects.GameObjects;

import java.util.ArrayList;

import world.World.TILE;

public class Floor {

	public static final World.TILE[][] PRE_MADE_FLOOR = {
			{ TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL },
			{ TILE.WALL, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.WALL },
			{ TILE.WALL, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.WALL },
			{ TILE.WALL, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.WALL },
			{ TILE.WALL, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.WALL },
			{ TILE.WALL, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.WALL},
			{ TILE.WALL, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.WALL },
			{ TILE.WALL, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.WALL },
			{ TILE.WALL, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.WALL },
			{ TILE.WALL, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON },
			{ TILE.WALL, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON, TILE.DONJON },
			{ TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL, TILE.WALL }};
			
	private World.TILE[][] tiles;
	private ArrayList<GameObjects> objects;
	private int startx, starty;

	private int depth;

	public Floor(int depth) {
		Generator gen = new Generator();
		tiles = gen.generate();
		startx = gen.getStartX();
		starty = gen.getStartY();
	}

	/**
	 * génère un floor qui est toujours pareil, principalement pour du testing
	 */
	public Floor() {
		tiles = PRE_MADE_FLOOR;
		startx = 0;
		starty = 0;
	}

	public ArrayList<GameObjects> getObjects() {
		return objects;
	}

	public void setObjects(ArrayList<GameObjects> objects) {
		this.objects = objects;
	}

	public World.TILE[][] getTiles() {
		return tiles;
	}
}
